### ISSUE TITLE
PATH issues with Vagrant ubuntu/xenial64

### ISSUE THREAD

**Issue by lswith** [puppetlabs/puppet_litmus#266] opened 2020-03-24 06:35 UTC
## Describe the Bug

The puppet-agent installs its binaries into the `/opt/puppetlabs/puppet/bin` folder. This folder is required to in the `PATH` for litmus tests to run correctly.

On Vagrant, it seems that this folder is not being added to the PATH.

## Expected Behavior

I expect `/opt/puppetlabs/puppet/bin` to be included in the `PATH`.

`PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/opt/puppetlabs/puppet/bin`

## Steps to Reproduce
Following the tutorial using vagrant:

```
# Provision ubuntu vagrant box
pdk bundle exec rake 'litmus:provision[vagrant, ubuntu/xenial64]'

# install the puppet agent
pdk bundle exec rake litmus:install_agent

# Check puppet is in the path
pdk bundle exec bolt command run 'env' -n 127.0.0.1:2222 -i inventory.yaml
...
Started on 127.0.0.1:2222...
Finished on 127.0.0.1:2222:
  STDOUT:
    SUDO_GID=1000
    MAIL=/var/mail/root
    USER=root
    HOME=/root
    OLDPWD=/home/vagrant
    LC_TERMINAL_VERSION=3.3.9
    SUDO_UID=1000
    LOGNAME=root
    USERNAME=root
    TERM=unknown
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
    LANG=en_US.UTF-8
    SUDO_COMMAND=/bin/sh -c cd && env
    SHELL=/bin/bash
    SUDO_USER=vagrant
    LC_TERMINAL=iTerm2
    PWD=/root
Successful on 1 target: 127.0.0.1:2222
Ran on 1 target in 0.36 sec
```

## Environment
 - Version 0.16.0
 - Platform Vagrant, Ubuntu Xenial64

## Additional Context

I have noticed the `configure_path(inventory_hash)` function which adds `/opt/puppetlabs/puppet/bin` to `/etc/environment`, however it seems that this file isn't being loaded.

```
pdk bundle exec bolt command run 'cat /etc/environment ' -n 127.0.0.1:2222 -i inventory.yaml
...
Started on 127.0.0.1:2222...
Finished on 127.0.0.1:2222:
  STDOUT:
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/opt/puppetlabs/puppet/bin
Successful on 1 target: 127.0.0.1:2222
Ran on 1 target in 0.64 sec
```

I have also noticed that removing the `run-as: root` option, seems to load the path correctly:

```
pdk bundle exec bolt command run 'echo $PATH' -n 127.0.0.1:2222 -i inventory.yaml

pdk (INFO): Using Ruby 2.5.7
pdk (INFO): Using Puppet 6.13.0
Deprecation Warning: The --nodes command line option has been deprecated in favor of --targets.
Started on 127.0.0.1:2222...
Finished on 127.0.0.1:2222:
  STDOUT:
    /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/opt/puppetlabs/puppet/bin
Successful on 1 target: 127.0.0.1:2222
Ran on 1 target in 0.61 sec
```

I think this is because the default path is set in the `/etc/sudoers` file:
```
   #
    # This file MUST be edited with the 'visudo' command as root.
    #
    # Please consider adding local content in /etc/sudoers.d/ instead of
    # directly modifying this file.
    #
    # See the man page for details on how to write a sudoers file.
    #
    Defaults	env_reset
    Defaults	mail_badpass
    Defaults	secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"

    # Host alias specification

    # User alias specification

    # Cmnd alias specification

    # User privilege specification
    root	ALL=(ALL:ALL) ALL

    # Members of the admin group may gain root privileges
    %admin ALL=(ALL) ALL

    # Allow members of group sudo to execute any command
    %sudo	ALL=(ALL:ALL) ALL

    # See sudoers(5) for more information on "#include" directives:

    #includedir /etc/sudoers.d
```

**Comment by DavidS** [comment] 2020-03-31 14:51
This is likely caused by https://github.com/puppetlabs/provision/pull/103 
short-term solution would be to revert that, long-term we need to better understand root vs non-root scenarios

**Comment by sanfrancrisko** [comment] 2021-06-21 11:18
Closing this given https://github.com/puppetlabs/provision/pull/103 was merged.

**Closed by sanfrancrisko** 2021-06-21 11:18 UTC
Labels: bug
