### ISSUE TITLE
environment not setup correctly on mac guests

### ISSUE THREAD

**Issue by jokreliable** [puppetlabs/puppet_litmus#399] opened 2021-03-11 06:02 UTC
https://github.com/puppetlabs/puppet_litmus/blob/0c4fb04db69bca2d0eb31f4e4bafe055b8018343/lib/puppet_litmus/rake_helper.rb#L235

This does not work on a mac guests any more.

I believe under linux (and other *nix), the pam module `pam_env` loads the environment from `/etc/environment`.  MacOS no longer loads that module by default (unsure how long ago this has been the case).

**Comment by jordanbreen28** [comment] 2023-07-24 14:07
Hey @jokreliable, thanks for raising this one, and apologies about the lack of engagement.
Due to the age of this issue, I am voting to close this.
Please re-open if necessary, but could I ask you add reproduction steps so I can take a proper look at this issue (if it still persists).
Thanks

**Closed by jordanbreen28** 2023-07-24 14:07 UTC
Labels: community

**Comment by jokreliable** [comment] 2023-07-26 02:47
Best I can tell, it's still an issue. I will try to spend some time to write down repro steps (how to build the image, etc...). Sadly, with newer version of macos, it's getting harder and harder to automate proper build steps without some hacks to inject some bootstrap into the machine. Keep this closed for now. Once I get this reset again, I'll reopen this issue (or make a new one).
