### ISSUE TITLE
beaker is installed

### ISSUE THREAD

**Issue by Dan33l** [puppetlabs/puppet_litmus#104] opened 2019-05-04 21:21 UTC
When i install gems with `bundle install --path .bundle/gems/`, all flavors of Beaker gems looks to be installed also. And some dependencies needs to compil.

Is it really necessary to get beaker fully installed when we want to use litmus ?

**Comment by tphoney** [comment] 2019-05-07 09:23
hi @Dan33l yeah that is by design for now, we will likely tackle this in the next phase. It will mean making changes to https://github.com/puppetlabs/puppet-module-gems and/or https://github.com/puppetlabs/pdk-templates/

**Comment by tphoney** [comment] 2019-05-07 09:24
thanks for the ticket, it will be tackled soon.

**Comment by tphoney** [comment] 2019-06-14 09:04
So i have PR's up for this, about to be merged. I'll let you know when its merged.

**Comment by tphoney** [comment] 2019-06-26 13:44
The changes have went to puppet-module-gems, and it has been released. So now by default litmus is installed as a development gem, and you do not need system tests.

**Closed by tphoney** 2019-06-26 13:44 UTC
